### ISSUE TITLE
Deferred purchase

### ISSUE THREAD

**Issue by fury21** [apphud/ApphudSDK#100]
Hey! I am trying to test deferred purchases. When I click the Buy button, I see the "Ask Permission" alert, when I click "Cancel" or "Ask", nothing happens, the ApphudDelegate does not fire and my activityIndicator is visible always. I have to process these purchases in func paymentQueue (_ queue: SKPaymentQueue, updatedTransactions transactions: [SKPaymentTransaction]) {}

How do I know if a deferred purchase has been used through the ApphudDelegate?
Is it possible to determine deferred purchase in Apphud.purchase() method?

<img width="657" alt="148984612-93ae3297-0fa0-47fa-9ff4-35474b867547" src="https://github.com/apphud/ApphudSDK/assets/30409500/3bc67749-fdfc-43eb-bc66-f923699ecb01">

**Comment by vlr-code** [comment]
Hi @fury21 
Apphud has a separate method for handling Deferred purchases in ApphudDelegate -> [handleDeferredTransaction](https://github.com/apphud/ApphudSDK/blob/98824094c6f304d7b2c167e5f72ac9e679fde699/ApphudSDK/Public/ApphudDelegate.swift#L80C35-L80C35)

**Comment by ren6** [comment]
@fury21 hi again! This issue has been fixed in v3.1.3. Thank you!
