### ISSUE TITLE
Apphud does not display the purchase when using the iPhone Simulator and Local StoreKit Testing.

### ISSUE THREAD

**Issue by roman-sundurov** [apphud/ApphudSDK#105]
I made the purchase on the simulator, and they showed up in the Manage Transaction Window, but it didn't appear on the simulator. Sometimes, Apphud displayed a Refunded subscription, but I didn't find a pattern. For some reason, it sometimes appeared.

The error is reproduced many times in the simulator when purchasing any subscriptions.

iOS v17.2
Xcode Version 15.1 (15C65)
ApphudSDK v3.1.4
![Screenshot 2023-12-21 at 2 46 49 AM](https://github.com/apphud/ApphudSDK/assets/68818066/ca4ad034-5bbf-4ff1-b0e3-e8ea017416a2)
![Screenshot 2023-12-21 at 2 47 07 AM](https://github.com/apphud/ApphudSDK/assets/68818066/cbfcba7f-014e-40ee-acbb-4baebe6f70b5)

**Comment by ren6** [comment]
@roman-sundurov Hi! there, did you try purchases on a new user? Try delete this one and try again.
Local StoreKit testing has lots of limitations, as it's not intended to test renewals, it's main purpose is to test your UI after successful purchase. See limitation here: https://docs.apphud.com/docs/testing-troubleshooting#local-storekit-testing
For smooth renewal process I suggest you testing Sandbox/Testflight purchases.

**Comment by roman-sundurov** [comment]
@ren6  Hi, nice to meet you! Yes, I've tried several options to fix it. These include:
1. Using real devices and different iOS/iPadOS simulators
2. Deleting users from Apphud
3. Reinstalling the application.

I followed all the steps from Apphud's documentation, but unfortunately, the problem persists. By the way, I didn't detect the issue when I used the sandbox scenario. I caught the issue only when I used Local StoreKit.

**Comment by ren6** [comment]
@roman-sundurov Sorry for long response and misleading you in the first answer.
I checked again with the docs. It appears that this is know limitation of Local StoreKit Testing, and cannot be improved. 
It just works as it is. See more limitations here: https://docs.apphud.com/docs/testing#local-storekit-testing
