### ISSUE TITLE
Apphud does not get back the subscriptions using Apphud.subscriptions() in the Widget (widget extension, SwiftUI, WidgetKit) on the real iPhone in Sandbox

### ISSUE THREAD

**Issue by roman-sundurov** [apphud/ApphudSDK#107]
I purchased the subscription on the real iOS device in sandbox mode, and it showed up in the Manage Transaction Window. But when I try to get subscriptions in the Widget (widget extension, SwiftUI, WidgetKit) and use the "**Apphud.subscriptions()**" method, I don't get any subscriptions. But when I use the same "**Apphud.subscriptions()**" method in the iOS app target, this method works and gets subscriptions.

iOS v17.2
Xcode Version 15.1 (15C65)
ApphudSDK v3.2.5
Frameworks: SwiftUI, WidgetKit
![Screenshot 2024-01-09 at 8 35 51 PM](https://github.com/apphud/ApphudSDK/assets/68818066/a2cf6458-af42-494e-a458-df4c8c732562)
![Screenshot 2024-01-09 at 8 36 27 PM](https://github.com/apphud/ApphudSDK/assets/68818066/d89b482e-71ab-4fd6-a8fd-bb17ac61fdb4)

**Comment by ren6** [comment]
@roman-sundurov hey, sorry for long response. You should have contacted us via the website support.
In your case, you have to initialize Apphud SDK with the same User ID and Device ID pair using `startManually` method. But for new apps (created after Feb 15), you would just have to initialize SDK with the same User ID.
Learn more how to pass data like User ID here:
https://emregurses.medium.com/sharing-data-between-app-and-extension-on-ios-2ff518b2ebe7
