### ISSUE TITLE
Purchase completion doesn't called

### ISSUE THREAD

**Issue by Nikiteizzz** [apphud/ApphudSDK#121]
Application is on store. After calling  Apphud.purchase(product, completion { ...} ) completion is never called. Using Swiftui

**Comment by vlr-code** [comment]
Hi @Nikiteizzz 
We require information regarding your Apphud project. Please contact our support team on the official website at your earliest convenience. https://apphud.com

Thank you for your prompt attention to this matter.

Best regards, Apphud team.
