### ISSUE TITLE
Apphud.isNonRenewingPurchaseActive(productIdentifier: "productID") cache issue

### ISSUE THREAD

**Issue by Panl** [apphud/ApphudSDK#22]
if I purchase a non-renewable subscription in testflight environment and then install the AppStore version without uninstalling the testflight version `let active = Apphud.isNonRenewingPurchaseActive(productIdentifier: "productID")` always return true

**Comment by ren6** [comment]
Yes, that's correct. Because your User ID has not changed. This is expected behaviour.
