### ISSUE TITLE
Disable IDFA collection

### ISSUE THREAD

**Issue by Panl** [apphud/ApphudSDK#23]
I call `Apphud.disableIDFACollection()` before `Apphud.start(apiKey: "")`, but when I submit app to app store connect, app store connect still says that my app contains IDFA, is there any way to solve this ?

**Comment by ren6** [comment]
Unfortunately not, you can check that it's being used to attribute installations to match previously served advertisements. That will be fine.

**Comment by Panl** [comment]
> Unfortunately not, you can check that it's being used to attribute installations to match previously served advertisements. That will be fine.

Noted, thanks
