### ISSUE TITLE
iOS 14 Beta Failed to load SKProducts from the App Store

### ISSUE THREAD

**Issue by uniqby** [apphud/ApphudSDK#27]
[12:15:06 PM] [Apphud] Failed to load SKProducts from the App Store, error: Error Domain=SKErrorDomain Code=0 "UNKNOWN_ERROR" UserInfo={NSLocalizedDescription=UNKNOWN_ERROR, NSUnderlyingError=0x6000008b4870 {Error Domain=ASDErrorDomain Code=507 "Error decoding object" UserInfo={NSLocalizedDescription=Error decoding object, NSLocalizedFailureReason=Attempted to decode store response}}}

**Comment by tnmendes** [comment]
Same issue here on iOS 14 Beta

`[Apphud] Failed to load SKProducts from the App Store, error: Error Domain=SKErrorDomain Code=0 "UNKNOWN_ERROR" UserInfo={NSLocalizedDescription=UNKNOWN_ERROR, NSUnderlyingError=0x6000018f2370 {Error Domain=ASDErrorDomain Code=507 "Error decoding object" UserInfo={NSLocalizedDescription=Error decoding object, NSLocalizedFailureReason=Attempted to decode store response}}}`

**Comment by Pehon1** [comment]
I've got the same error 
Failed to load SKProducts from the App Store, error: Error Domain=SKErrorDomain Code=0 "UNKNOWN_ERROR" UserInfo={NSLocalizedDescription=UNKNOWN_ERROR, NSUnderlyingError=0x60000391d770 {Error Domain=ASDErrorDomain Code=507 "Error decoding object" UserInfo={NSLocalizedDescription=Error decoding object, NSLocalizedFailureReason=Attempted to decode store response}}}

**Comment by chuiizeet** [comment]
Same error on xcode 12.0 (12A7209)

`Failed to load SKProducts from the App Store, error: Error Domain=SKErrorDomain Code=0 "UNKNOWN_ERROR" UserInfo={NSLocalizedDescription=UNKNOWN_ERROR, NSUnderlyingError=0x600000714c30 {Error Domain=ASDErrorDomain Code=507 "Error decoding object" UserInfo={NSLocalizedDescription=Error decoding object, NSLocalizedFailureReason=Attempted to decode store response}}}
`

**Comment by dashvlas** [comment]
Same here :(

iOS 14.2
Xcode 12.0

**Comment by fatihyildizhan** [comment]
I have the same error :(

**Comment by tnmendes** [comment]
Update to the latest version of this pod it should fix the issue

**Comment by ren6** [comment]
This is now fixed. Apphud supports fetching products in iOS Simulator using Local StoreKit Configuration file.
https://docs.apphud.com/testing/ios#local-storekit-testing
