### ISSUE TITLE
Crash "Unexpectedly found nil while implicitly unwrapping an Optional value"

### ISSUE THREAD

**Issue by atom-wintermute** [apphud/ApphudSDK#37]
AppHud version 0.18.4
Crash happens after calling `refreshStoreKitProducts` method

<img width="701" alt="Screenshot 2021-01-28 at 09 05 19" src="https://user-images.githubusercontent.com/18706680/106097780-f754c700-6148-11eb-91ff-9381aea99106.png">

<img width="1250" alt="Screenshot 2021-01-28 at 09 13 09" src="https://user-images.githubusercontent.com/18706680/106097837-0e93b480-6149-11eb-94a9-31954af3af6c.png">

**Comment by ren6** [comment]
Hi!
You should first initialize SDK by calling Apphud.start.. And then use this method.
By the way, this method should only be used when your Apphud.products() array is nil, but you need to display your Purchase screen.

**Comment by ren6** [comment]
Closed due to outdated.
