### ISSUE TITLE
Requires minimum iOS 11.2

### ISSUE THREAD

**Issue by zhuravel-sergey** [apphud/ApphudSDK#4]
"Apphud SDK requires minimum iOS 11.2" - are you serious? 

My application supports iOS 9 and above, for the sake of your SDK I will not raise the "Deployment Target" version. Since I have many clients on iOS 9 and 10.
How can I use the SDK and your service now?

**Comment by denis-minnetdinov** [comment]
Hi! Unfortunately iOS 11.2 is a minimal iOS version we currently support. We will possibly add older iOS versions support later.
