### ISSUE TITLE
Corner case when user is not registered and products not loaded automatically

### ISSUE THREAD

**Issue by ulitiy** [apphud/ApphudSDK#42]
1. first launch after install without wifi
2. wait 5 minutes
3. enable wifi
4. try to subscribe

because of the max number of attempts Apphud will give up on trying to register user and fetch products.

I use `refreshStoreKitProducts` to force it but with SwiftUI it's a bit awkward.

I think there shouldn't be a limit, also 30+ seconds retry is too much to wait for the user if he goes online.
I understand that you try to reduce load on your servers but there is no load if there's no connection. Maybe you should check the error generated by the request.

**Comment by ren6** [comment]
@ulitiy issue has been fixed in [1.2.1](https://github.com/apphud/ApphudSDK/releases/tag/1.2.1)

**Comment by ulitiy** [comment]
This issue is still present for cases when apphud is unavailable for reasons other than internet disconnected.
