### ISSUE TITLE
'shared' is unavailable in application extensions for iOS: Use view controller based solutions where appropriate instead.

### ISSUE THREAD

**Issue by MikaelMelkonyan** [apphud/ApphudSDK#53]
<img width="1422" alt="Screenshot 2021-07-25 at 18 38 39" src="https://user-images.githubusercontent.com/16278100/126904882-5cbedbdc-bec3-495a-abfe-5cc6e340c313.png">

Apphud SDK - 2.2.1
Xcode - 13.0 beta 3
Swift - 5
Min iOS Deployment target = 14.0

**Comment by ren6** [comment]
Hi @MikaelMelkonyan it seems like you did install Apphud SDK on application extension. It should be only installed to your app's main target. Please double check your Podfile and split it into two separate targets. One for main app, other target for extension.

**Comment by MikaelMelkonyan** [comment]
> Hi @MikaelMelkonyan it seems like you did install Apphud SDK on application extension. It should be only installed to your app's main target. Please double check your Podfile and split it into two separate targets. One for main app, other target for extension.

I'm sorry. I did not mention that I use Swift Package manager. 
I would like to create an Apple watch application and use there Apphud. Is it possible? 😇

Thank you

**Comment by vlr-code** [comment]
> I would like to create an Apple watch application and use there Apphud. Is it possible?
In the near future it is planned

**Comment by tnmendes** [comment]
Any update? I am trying to implement a widget that requires apphud
