### ISSUE TITLE
Deferred purchase

### ISSUE THREAD

**Issue by fury21** [apphud/ApphudSDK#68]
Hey! I am trying to test deferred purchases. When I click the Buy button, I see the "Ask Permission" alert, when I click "Cancel" or "Ask", nothing happens, the ApphudDelegate does not fire and my activityIndicator is visible always. I have to process these purchases in func paymentQueue (_ queue: SKPaymentQueue, updatedTransactions transactions: [SKPaymentTransaction]) {}

How do I know if a deferred purchase has been used through the ApphudDelegate?
<img width="657" alt="Снимок экрана 2022-01-11 в 19 38 34" src="https://user-images.githubusercontent.com/30409500/148984612-93ae3297-0fa0-47fa-9ff4-35474b867547.png">

**Comment by fury21** [comment]
Asked 18 days ago...

**Comment by vlr-code** [comment]
Hi, we will add `deferred purchase` in delegate in the next update
