### ISSUE TITLE
iPhone SE (14.4) simulator, AppHud 2.5.7 not loading SKProducts

### ISSUE THREAD

**Issue by fury21** [apphud/ApphudSDK#76]
Hi!
I try to get SKProducts from ApphudProduct, but got nil in iPhone SE 14.4, before all worked fine.

My steps:
 Apphud.paywallsDidLoadCallback { paywalls in
            // retrieve default paywall
            let paywall = paywalls.first(where: { $0.isDefault })
            var products: [ApphudProduct] = []
            
            // retrieve the products [ApphudProduct] from current paywall
            if let paywall = paywall {
                products = paywall.products
                
                for product in paywall.products {
                    print("test:", product.productId, product.skProduct) 
                }
            }
        }

what i get: "test: com.kushman.nevergame.annual nil", but in other simulators, like iPhone 13 pro max 15.2 i got: "com.kushman.nevergame.annual Optional(<SKProduct: 0x600002905270>)"

Can u help me?

**Comment by vlr-code** [comment]
Hi, it seems to be a problem with a specific iOS version on simulator, can you provide more details?

**Comment by Neeraj204** [comment]
@fury21 did you find any solution for this? I am facing the same issue. @vlr-code @ren6 Kindly let us know if there is fix available for the same.
