### ISSUE TITLE
macOS: 'ApphudInternal' is only available in macOS 10.14.4 or newer

### ISSUE THREAD

**Issue by uniqby** [apphud/ApphudSDK#84]
Can not build macOS target after updating AppHud to **2.8.1**. 

AppHud SDK: 2.8.1
macOS deployment target: 12.0

<img width="1206" alt="Screen Shot 2022-05-09 at 13 52 28" src="https://user-images.githubusercontent.com/1488394/167404387-1efd55af-4692-4cf0-b286-bacc65af9362.png">

**Comment by ren6** [comment]
Fixed

**Comment by uniqby** [comment]
![Uploading Screenshot 2022-12-29 at 16.40.31.png…]()

**Comment by uniqby** [comment]
AppHud SDK version: 2.8.8

<img width="1777" alt="Screenshot 2022-12-29 at 16 41 34" src="https://user-images.githubusercontent.com/1488394/209976272-139c235d-b028-4a8b-ad70-96be0e19914b.png">

**Comment by satanworker** [comment]
I have the same issue on the last version of Apphud 2.8.1
